config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #devise_for :teachers
  devise_for :teachers, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'subscription_plan', :to => 'home#subscription'
  get 'blank_label', to: 'home#blank_label'
  get 'trial', to: 'home#trial'

  resources :subjects do
    collection do
      get :fetch_children
    end 
  end
  resources :children
  resources :teachers do
    collection do
      post  :create_teacher
      get :teacher_subscription
    end
  end
  resources :sheets do
    collection do
      get :fetch_children
      get :report
      get :report_details
    end 
    member do
      get :child_detail
      patch :update_detail
    end
  end

  resources :subscriptions do
    collection do
      post :checkout
      get :thankyou
    end
  end
  get '*path' => redirect('/')
end

app/models/sheet.rb
class Sheet < ApplicationRecord
  belongs_to :teacher
  has_many :details, :dependent => :destroy
  belongs_to :subject

  accepts_nested_attributes_for :details, allow_destroy: true

  validates :title, :subject_id, :teacher_id, :date, presence: true


  def self.get_details(id)
    find_by_sql("select sheets.id, children.id as children_id, children.name, sheets.title, grades.abr as grade_name, grades.color, details.comment from subjects INNER JOIN students ON subjects.id = students.subject_id and subjects.id = #{id} INNER JOIN children ON children.id = students.child_id INNER JOIN details ON details.child_id = children.id INNER JOIN sheets ON sheets.id = details.sheet_id FULL JOIN grades ON grades.id = details.grade_id where sheets.subject_id = #{id} order by sheets.created_at DESC, children.name,grade_name, details.comment")
  end

  def sanitize_comment
    comment? ? ActionView::Base.full_sanitizer.sanitize(comment) : ''
  end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  before_action :set_sheet, only: [:index]
  before_action :set_subject, only: [:index, :report_details]
  load_and_authorize_resource

  def index
    @subjects = current_teacher.subjects
    if params[:subject_id]
      @sheets = current_teacher.sheets.where(subject_id: params[:subject_id])
    end
  end

  def report_details
    if params[:subject_id]
      @sheets = Sheet.get_details(params[:subject_id])
      @children = @subject.children.order('name').ids
    end
  end

  def new
    @objectives = current_teacher.sheets.order('created_at DESC')
  end

  def create
    if @sheet.details.present? && @sheet.save
      flash[:notice] = "Saved successfully"
      redirect_to :action => 'new'
    else
      @errors = @sheet.errors.full_messages
    end
  end

  def destroy
    @sheet.destroy
    @objectives = current_teacher.sheets.order('created_at DESC')
  end

  def show
    @details = @sheet.details
  end

  def fetch_children
    @details = @sheet.details.joins(:child).order("children.name asc")
    @detail = @details.first
  end

  def child_detail
    @detail = @sheet.details.find_by_id(params[:detail])
  end

  def update_detail
    @sheet = Sheet.find(params[:sheet_id])
    @detail = @sheet.details.find_by_id(params[:detail_id])
    @detail.update_attributes(comment: params[:detail][:comment], grade_id: params[:detail][:grade_id]) if params[:detail_ids].blank?
    @sheet.details.where(id: params[:detail_ids]).update_all(comment: params[:detail][:comment], grade_id: params[:detail][:grade_id])
    respond_to do |format|
      format.js 
      format.json do
        render json: { text: params[:detail][:comment], ids: params[:detail_ids], id: @detail.try(:id) }.to_json
      end
    end
  end

  def report
    @sheets = current_teacher.sheets
    @subjects = current_teacher.subjects
  end

  private

  def set_sheet
    if params[:id].present?
      @sheet = current_teacher.sheets.find_by_id(params[:id])
    end
  end

  def set_subject
    @subject = current_teacher.subjects.find_by_id(params[:subject_id])
  end

  def sheet_params
    params.require(:sheet).permit(:title, :subject_id, :teacher_id, :date, details_attributes: [:comment, :child_id, :grade_id])
  end
end

app/views/sheets/_form_section.html.erb
<%= form_for @detail, url: update_detail_sheet_path(@sheet), remote: true, id: 'detailForm' do |f| %>
  <div class="multiselect-child-ids"></div>
  <div class="col-md-12">
    <div class="col-md-10">
      <%= label_tag @detail.child.name, nil, :class => "control-label" %>
      <%= f.text_area :comment, class: 'form-control ckeditor', rows: "5", id: "dictation"%>
    </div>
    <div class="col-md-2 col-sm-2">
      <%= f.submit 'Print Label', class: "btn btn-primary print-label", id: "print-label" %>
      <button type="button" class="btn btn-primary print-label clear-label">Clear Label</button>

      <%= f.submit 'Save Label', class: "btn btn-primary print-label"%>
    </div>
  </div>
    <%= hidden_field_tag "detail_id", @detail.id%>
    <%= hidden_field_tag "sheet_id", @sheet.id %>
  <div class="col-sm-12 col-md-12">
    <div class="col-sm-4 grade-abr">
      <% @sheet.subject.grades.order(marks: :desc).each do |grade| %>
        <div class="radio radio-margin">
          <label><%= f.radio_button :grade_id , grade.id, "data-marks" => grade.abr, onclick: "getGrade('#{grade.id}', '#{grade.color}')", "data-grade" => grade.name.downcase, "data-color" => grade.color %><%= grade.name %></label>
        </div>
      <% end %>
    </div>
    <div class="col-md-6 col-sm-6 grade-margin">
      <h5>Current Grade</h5>
      <b><%= text_field_tag :marks, "", class: 'form-control text-size', style: "background-color: #{@detail&.grade&.color}", disabled: true, value: @detail&.grade&.abr %></b>

    </div>
    <!-- <div class="col-md-2 col-sm-2">
      <%#= f.submit 'Print Label', class: "btn btn-primary print-label", id: "print-label" %>
      <button type="button" class="btn btn-primary print-label clear-label">Clear Label</button>
    </div> -->
  </div>
<% end %>


<script type="text/javascript">
  $('.ckeditor').ckeditor({
    // optional config
  })

  $("#record-btn").show()
  function getGrade(id, color){
    if ($("#detail_grade_id_"+id).is(":checked")) {
      var data = $("#detail_grade_id_"+id).data("marks")
      $(".text-size").val(data)
      $(".text-size").css("background-color", color);
    }
  }
  $('.clear-label').click(function(){
    $("#dictation").val('')
  })
  $('#print-label').click(function(){
    if ($('.multiple-child:checkbox:checked').size() > 0) {
      $('.multiple-child:checkbox:checked').each(function () {
        PrintDiv($("#dictation").val())
      })
    } else {
      PrintDiv($("#dictation").val())
    }
  })
  function PrintDiv(text) {
    var popupWin = window.open('', '_blank', 'width=300,height=300');
    popupWin.document.open();
    if (text.indexOf('span') == -1){
      popupWin.document.write('<html><body>' + '<span style="font-family:Comic Sans MS,cursive">' + text + '</span>' + '</html>');

    } else {
      popupWin.document.write('<html><body>' + text + '</html>');
    }

    var document_focus = false;
    $(document).ready(function() { popupWin.window.print();document_focus = true; });
        setInterval(function() { if (document_focus === true) { popupWin.window.close(); }  }, 300);
    // popupWin.document.close();

  }

  if (annyang) {
    // var isRecording = false; // create var to track recording state
    var names = []; //insert names for annyang commands
    var grades = [];
    var numberGrades = [];
    $('.student-list').find('a').each(function() {
      names.push(this.text)
    })
    $(':radio').each(function(){
      if (Number.isInteger($(this).data("grade"))) {
        numberGrades.push($(this).data("grade").toString())
      }
      else {
        grades.push($(this).data("grade").toLowerCase())
      }
    });

    // define the functions our commands will run.

    var question = function() {
      str = $("#dictation").val()
      //$("#dictation").val(str + '?')
      CKEDITOR.instances.dictation.insertText('?');
    };

    // var remove = function() {
    //   str = $("#dictation").val()
    //   $("#dictation").val(str.slice(0,-1))
    // };

    var mark = function() {
      str = $("#dictation").val()
      //$("#dictation").val(str+'!')
      CKEDITOR.instances.dictation.insertText('!');
    };

    var comma = function() {
      str = $("#dictation").val()
      //$("#dictation").val(str + ', ')
      CKEDITOR.instances.dictation.insertText(', ');
    };

    var colon = function() {
      str = $("#dictation").val().replace(/\s+$/, '')
      //$("#dictation").val(str + ':')
      CKEDITOR.instances.dictation.insertText(':');
    };

    var semicolon = function() {
      str = $("#dictation").val().replace(/\s+$/, '')
      //$("#dictation").val(str + '; ')
      CKEDITOR.instances.dictation.insertText('; ');
    };

    var hyphen = function() {
      str = $("#dictation").val().replace(/\s+$/, '')
      //$("#dictation").val(str + '-')
      CKEDITOR.instances.dictation.insertText('-');
    };

    var nextLine = function() {
      str = $("#dictation").val()
      //$("#dictation").val(str + '\n ')
      CKEDITOR.instances.dictation.insertText('\n');
    };

    var stop = function() {
      str = $("#dictation").val().replace(/\s+$/, '')
      //$("#dictation").val(str + '. ')
      CKEDITOR.instances.dictation.insertText('. ');
    };

    var stopped = function() {
      str = $("#dictation").val().replace(/\s+$/, '')
      //$("#dictation").val(str + '. ')
      CKEDITOR.instances.dictation.insertText('. ');
    };


    var writeIt = function(repeat) {
      if (names.includes(repeat)) {
        $.ajax({
          url: $("#"+repeat).attr('href'),
          //orther options ...
          success: function(data){
              $("#"+repeat).click()
          }
        });
      }else if ((grades.includes(repeat)) || (numberGrades.includes(repeat))) {
        $("input[data-grade='"+ repeat +"']").click()
        $(".text-size").val($("input[data-grade='"+ repeat +"']").data("marks"))
        $(".text-size").css("background-color", $("input[data-grade='"+ repeat +"']").data("color"));
      }else if (repeat == "clear label") {
        $("#dictation").val('')
      }else if (repeat == "print label") {
        var test = []
        dataSet = $('.edit_detail').serializeArray().reduce( (result, input) => {
                  if (input.name == 'detail_ids[]'){
                    test.push(input.value)
                    result[input.name] = test
                  }else {
                    result[input.name] = input.value;
                  }
                  return result;
                  }, {}
                );
        $.ajax({
          url: '<%= update_detail_sheet_path(@sheet) %>',
          type: 'patch',
          dataType: 'json',
          data: dataSet,
          success: function(data) {
            $('.multiple-child').prop( "checked", false );
            $("#ckbCheckAll").prop("checked", false)
            if (data.ids == null) {
              PrintDiv(data.text)
              $(".color-"+data.id).css("color", "green");
            }else {
              data.ids.forEach(function(id) {
                $(".color-"+id).css("color", "green");
                PrintDiv(data.text)
              })
            }

          }
        });
      }else if (repeat == "save label") {
        var test = []
        dataSet = $('.edit_detail').serializeArray().reduce( (result, input) => {
                  if (input.name == 'detail_ids[]'){
                    test.push(input.value)
                    result[input.name] = test
                  }else {
                    result[input.name] = input.value;
                  }
                  return result;
                  }, {}
                );

        $.ajax({
          url: '<%= update_detail_sheet_path(@sheet) %>',
          type: 'patch',
          dataType: 'json',
          data: dataSet,
          success: function(data) {
            $('.multiple-child').prop( "checked", false );
            $("#ckbCheckAll").prop("checked", false)
            if (data.ids == null) {
              $(".color-"+data.id).css("color", "green");
              alert("save comment successfully")
            }else {
              data.ids.forEach(function(id) {
                $(".color-"+id).css("color", "green");
              })
              alert("save comments successfully")
            }
          }
        });
      }
      else{
        CKEDITOR.instances.dictation.focus();
        var range = CKEDITOR.instances.dictation.createRange();
        range.moveToElementEditEnd(range.root);
        CKEDITOR.instances.dictation.getSelection().selectRanges([range]);
        str = $("#dictation").val()
        if (str == ""){
          text = repeat.substr(0,1).toUpperCase()+repeat.substr(1)
          //$("#dictation").val(text)
          CKEDITOR.instances.dictation.insertText(text);
        } else if ((str[str.length-2]=='.') || (str[str.length-1]=='.') || (str[str.length-7] == '.')){
          text = repeat.substr(0,1).toUpperCase()+repeat.substr(1)
          //$("#dictation").val(str +' '+text)
          CKEDITOR.instances.dictation.insertText(' '+text);
        } else if (str[str.length-1]=='!'){
          text = repeat.substr(0,1).toUpperCase()+repeat.substr(1)
          //$("#dictation").val(str +' '+text)
          CKEDITOR.instances.dictation.insertText(' '+text);
        } else if (str[str.length-1]=='?'){
          text = repeat.substr(0,1).toUpperCase()+repeat.substr(1)
          //$("#dictation").val(str +' '+text)
          CKEDITOR.instances.dictation.insertText(' '+text);
        } else if (repeat=='.'){
          //$("#dictation").val(str +repeat +' ')
          CKEDITOR.instances.dictation.insertText(repeat +' ');
        } else if (str[str.length-1]=='-'){
          //$("#dictation").val(str +repeat +' ')
          CKEDITOR.instances.dictation.insertText(repeat +' ');
        } else {
          //$("#dictation").val(str+' '+repeat)
          if (str.slice(str.length - 13, str.length-7) == '<br />'){
            CKEDITOR.instances.dictation.insertText(repeat);
          } else {
            CKEDITOR.instances.dictation.insertText(' '+repeat);
          }
        }

      }
      //$("#dictation").text(repeat);
    }
    // define our commands.
    // * The key is what you want your users to say say.
    // * The value is the action to do.
    //   You can pass a function, a function name (as a string), or write your function as part of the commands object.exclamation mark
    var commands = {
      'full stop (there)':        stop,
      'fullstop (there)':        stopped,
      'exclamation mark (there)':        mark,
      'question mark (there)':        question,
      'next line (there)':        nextLine,
      'comma (there)':        comma,
      'hyphen (there)':       hyphen,
      'semicolon (there)':    semicolon,
      'colon (there)':        colon,
      '*repeat':        writeIt
    };
    names.forEach(function(name) {
      commands[name] = function() {
        $.ajax({
          url: $("#"+name).attr('href'),
          //orther options ...
          success: function(data){
              $("#"+name).click()
          }
        });
      }
    })

    grades.forEach(function(grade) {
      commands[grade] = function() { grade }
    })

    annyang.debug();                // turn on debugging (console messages)

    // Add voice commands to respond to
    annyang.addCommands(commands);

  } else {
    $("#dictation").text('Sorry, browser not supported.');
  }

</script>

app/views/sheets/_objective_list.html.erb
<b>Previous Objectives</b>
<%= select_tag :sheet, options_for_select(sheets),:prompt => "Select Objective", class: 'form-control sheet_subject_id' %><br>

<script type="text/javascript">
  $(".sheet_subject_id").change(function(){
    $.ajax({
      data: { 'id' : this.value },
      url: "<%= fetch_children_sheets_path %>",
      //orther options ...
      success: function(data){
          //$("#floors_select").html(data);
      }
    });
  })
</script>

app/views/sheets/_objectives_table.html.erb
<% @objectives.each do |objective| %>
  <tr>
    <td width="200"><%= objective.title %></td>
    <td><%= objective.date.strftime('%d/%m/%Y') %></td>
    <td><%= objective.subject.name %></td>
    <td>
      <%= link_to 'Delete', sheet_path(objective), :method => :delete, data: { confirm: 'Are you sure?' }, remote: true, class: "btn btn-default" %>
      <%= link_to 'Mark', sheets_path(id: objective.id), class: "btn btn-default" %>
    </td>
  </tr>
<% end %>

app/views/sheets/_report.html.erb
<style type="text/css">
  table.secondtable{
    table-layout: fixed;
    width: 200px;  
  }
  table.firsttable{
    table-layout: fixed;
    width: 158px;  
  }
.secondtable,th {
      overflow: hidden;
      width: 100px;
      height:100px; 
      

  }  
  .firsttable,th {
      overflow: hidden;
      width: 100px;
      height:100px; 

  }  

  .secondtable, td {
      overflow: hidden;
      width: 200px;
      padding: 0 5px 1px !important;
      font-size: 12px;
  }   
</style>
<%headers = @sheets.map{|sheet| sheet if sheet.children_id == @children.first}.compact%>
  <div class="col-md-2 col-sm-6 col-xs-6" style="overflow:hidden; padding: 0px !important">
    <table class="table table-bordered table-striped firsttable">
      <thead>
        <div>
          <th style="font-size:10px"><b>Name</b></th>
        </div>
      </thead>
      <tbody>
        <%@children.each do |child|%>
          <%list = @sheets.map{|sheet| sheet if sheet.children_id == child}.compact%>
          <tr>
            <td><%= list.first.name.truncate(23) rescue nil%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-10 col-sm-6 col-xs-6" style="padding: 0px !important">
    <div class="table-responsive table-hover ">
      <table class="table table-bordered table-striped objective-report-table secondtable">
      <% @title_count = headers.count %>
       <thead>
          <% headers.each do |sheet| %>
          
            <th style="font-size:10px; text-align: center;">
              <% @divdata = find_grades_persents(sheet) %>
              <% if @divdata != nil %>
                <% @div =  "#{@divdata}".gsub('"', '') %>
                <% @divchangeData =  "#{@div}".gsub(']', '') %>
                <div data-original-title="<%= "#{@divchangeData}".gsub('[', '') %>" data-toggle="tooltip">
                  <b><%= sheet.title.truncate(67) %></b>
                </div>
              <% end %>     
            </th>
          <% end %>
        </thead>
        <tbody>
          <%@children.each do |child|%>
            <%list = @sheets.map{|sheet| sheet if sheet.children_id == child}.compact%>
            <% @child_count = list.count %>
            <% @data = list.first.name.truncate(23) rescue nil %>
            <% j =  @title_count - @child_count %>
            <% i = 0 %>
            <tr>
              <% list.each do |sheet| %>
                <td style="text-align: center; background: <%= sheet.color%>">
                  <div data-original-title="<%= sheet.sanitize_comment %>" data-toggle="tooltip">
                    <%= sheet.grade_name.present? ? sheet.grade_name : 'None' %>
                  </div>
                </td> 
              <% end %>
              <% if (j != 0) %>
                <% for i in i...j %>
                  <td style="text-align: center;">
                      <%= 'Absent' %> 
                  </td>
                <% end %> 
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/sheets/child_detail.js.erb
$(".form-section").html("<%= escape_javascript(render 'form_section') %>")
$('.multiple-child').prop( "checked", false );
detailID = "<%= @detail.id %>"
// $('#detail-id-'+detailID).prop( "checked", true );
//$('.multiselect-child-ids').append("<input type='hidden' name='detail_ids[]'" + "value='" + detailID + "' >")

app/views/sheets/destroy.js.erb
$("#objectives-list").html("<%= escape_javascript(render 'objectives_table') %>")

app/views/sheets/fetch_children.js.erb
$(".student-list").html("<%= escape_javascript(render 'children') %>")
$(".form-section").html("<%= escape_javascript(render 'form_section') %>")
//annyang.abort()
//$("#record-btn").show()
//$('.multiple-child').first().prop( "checked", true );
detailID = $('.multiple-child').first().val()
//$('.multiselect-child-ids').append("<input type='hidden' name='detail_ids[]'" + "value='" + detailID + "' >")

app/views/sheets/index.html.erb
<div class="row custom-table-position">
  <div class="well col-md-12 col-sm-12 col-xs-12 reports">
    <div class="col-md-7 col-sm-7 col-xs-7">
      <%= form_tag sheets_path, :method => "get",:remote=> true do %>
        <b>List of Subjects</b>
        <%= select_tag :subject, options_for_select(subjects),:prompt => "Select Subject", class: 'form-control subject_id' %><br>
        <div class="filter-subject"><%= render "objective_list" %></div>
      <% end %>
      <button type="button" class="btn btn-sm" style="float:right; display: none;" id="record-btn"><span>Start Speech</span></button>
      <div class="form-group form-section">
        
      </div>
    </div>
    <div class="col-md-5 col-sm-5 col-xs-5 student-list">
      <%= render "children" %>
    </div>
  </div><br>
</div>

<% if @sheet.present? %>
  <script type="text/javascript">
    $( document ).ready(function() { 
      subject_id = "<%= @sheet.subject.id %>" 
      sheet_id = "<%= @sheet.id %>"
      sendAjaxRequest({ 'subject_id' : subject_id }, "<%= sheets_path %>", 'script', false)
      $("#subject").val(subject_id)
      sendAjaxRequest({ 'id' : sheet_id }, "<%= fetch_children_sheets_path %>", '', false)
      $("#sheet").val(sheet_id)
    });
  </script>
<% end %>

<script type="text/javascript">
  $(".subject_id").change(function(){
    sendAjaxRequest({ 'subject_id' : this.value }, "<%= sheets_path %>", 'script', true)
  })

  var isRecording = false; 
  $("#record-btn").click(function(event){
    event.preventDefault();
    // if we're recording when the button is clicked
    if(isRecording) {
      annyang.abort();            // stop listening
      isRecording = false;          // set recording var to false
      $("span",this).text('Start Speech');      // change btn text
      $(this).removeClass('btn-danger');    // turn off red class
      
    // if we're not recording when the button is clicked
    } else {
      //annyang.abort()
      annyang.start();            // start listening
      isRecording = true;           // set recording var to true
      $("span",this).text('Stop');      // change btn text
      $(this).removeClass('btn-primary');   // turn off blue class
      $(this).addClass('btn-danger');     // turn on red class
    }
  });

  function sendAjaxRequest(data, url, data_type, is_async) {
    $.ajax({
      data: data,
      url: url,
      dataType: data_type,
      async: is_async,
      success: function(data){
      }
    });
  }
</script>

app/views/sheets/index.js.erb
$(".filter-subject").html("<%= escape_javascript(render 'objective_list') %>")
$(".form-section").html("")
$("#record-btn").hide()

app/views/sheets/new.html.erb
<div class="row custom-table-position">
  
  <div class="">
    <div class="well">
      <h2>New Objective </h2>
      <%= form_for @sheet, html: { style: "display:inline;" } do |f| %>
      <div class="form-group">
        <div class="row">
          <div class="col-md-6">
            <%= f.label :title %><br />
            <%= f.text_field :title, autofocus: true, class: 'form-control', placeholder: 'Name', required: true %>
          </div>
          <div class="col-md-3">
            <%= f.label :date %><br />
            <%= f.date_field :date,   class: 'form-control', required: true %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-md-6">
            <%= f.label :subject %><br />
            <%= f.select :subject_id, options_for_select(current_teacher.subjects.collect { |c| [c.name, c.id]}), {:prompt => "Select Subject"},   class: 'form-control', required: true %>
          </div>
        </div>
        
      </div>
      <div class="form-group student-list">
        <%#= render "children" %>
      </div>
      <div class = "">
        <div class="actions">
          <%= f.submit  "Save", class: 'btn btn-primary btn-sm' %>
        </div>
      </div>
      <% end %>
    </div>
    <div class="well table-responsive">
      <b>Objectives List</b>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Title</th>
            <th>Date</th>
            <th>Subject</th>
            <td>Action</td>
          </tr>
        </thead>
        <tbody id="objectives-list">
          <%= render "objectives_table" %>
        </tbody>
      </table>
    </div>

  </div>
</div>

<script type="text/javascript">
  $("#sheet_subject_id").change(function(){
    var id = this.value
    $.ajax({
      data: { 'id' : this.value },
      url: "<%= fetch_children_subjects_path %>",
      //orther options ...
      success: function(data){
          //$("#floors_select").html(data);
      }
    });
  })
</script>

app/views/sheets/report.html.erb
<div class="row custom-table-position">
  <div class="col-md-12">
    <%= select_tag :subject, options_for_select(subjects),:prompt => "Select Subject", class: 'form-control subject_id ' %><br>
  </div>
  <div class="col-md-12 report-section">
  </div>
</div>

<script type="text/javascript">
  $(".subject_id").change(function(){
    $.ajax({
      data: { 'subject_id' : this.value, 'report' : 'true' },
      url: "<%= report_details_sheets_path %>",
      dataType: 'script',
      //orther options ...
      success: function(data){
          //$("#floors_select").html(data);
      }
    });
  })
</script>

app/views/sheets/report_details.js.erb
<%if @sheets.present? %>
  $(".report-section").html("<%= escape_javascript(render 'report') %>")
  $("[data-toggle='tooltip']").tooltip();
<%else%>
  $(".report-section").html("")
<%end%>

app/views/sheets/show.html.erb
<div class="marginleft11">
  <% if @details.present? %>
    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <th>Student Name</th>
        <th>Objective Title</th>
        <th>Grades</th>
        <th>Subject</th>
      </tr>
      </thead>
      <tbody>
        <% @details.each do |detail| %>
          <tr>
            <td><%= detail.child.name %></td>
            <td><%= detail.sheet.title %></td>
            <td><%= detail.grade.present? ? detail.try(:grade).try(:name) : 'Not assigned' %></td>
            <td><%= detail.sheet.subject.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/sheets/update_detail.js.erb
$(".form-section").html("<%= escape_javascript(render 'form_section') %>")
// annyang.abort()

// $("span","#record-btn").text('Start Speech');
// $("#record-btn").removeClass('btn-danger');
$('.multiple-child').prop( "checked", false );
//detailID = "<%= @detail.id %>"
$('.multiselect-child-ids').html()
<%if params[:detail_ids].present? %>
	<% params[:detail_ids].each do |id| %>
		$(".color-<%= id %>").css("color", "green");
	<% end %>
<% else %>
	$(".color-<%= @detail.id %>").css("color", "green");
<% end %>
$("#ckbCheckAll").prop("checked", false)
// $('#detail-id-'+detailID).prop( "checked", true );
//$('.multiselect-child-ids').append("<input type='hidden' name='detail_ids[]'" + "value='" + detailID + "' >")