config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #devise_for :teachers
  devise_for :teachers, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'subscription_plan', :to => 'home#subscription'
  get 'blank_label', to: 'home#blank_label'
  get 'trial', to: 'home#trial'

  resources :subjects do
    collection do
      get :fetch_children
    end 
  end
  resources :children
  resources :teachers do
    collection do
      post  :create_teacher
      get :teacher_subscription
    end
  end
  resources :sheets do
    collection do
      get :fetch_children
      get :report
      get :report_details
    end 
    member do
      get :child_detail
      patch :update_detail
    end
  end

  resources :subscriptions do
    collection do
      post :checkout
      get :thankyou
    end
  end
  get '*path' => redirect('/')
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_teacher! , :except => [:subscription, :trial]
  def index
    @subjects = current_teacher.subjects
    @children = current_teacher.children
    @details_count = current_teacher.details.updated_in_between((Time.zone.now - 30.days), Time.zone.now).count
  end

  def subscription
  end

  def blank_label
  end

  def trial
  end

end

app/views/home/blank_label.html.erb
<div class="row custom-table-position">
  <div class="well col-md-12 col-sm-12 col-xs-12 reports">
    <div class="col-md-8 col-sm-8 col-xs-8">
      <h3>Blank Label</h3>
      <div class="form-group form-section">
        <%= text_area_tag :comment,'', class: 'form-control ckeditor1', rows: "5", id: "dictation1"%>
        <button type="button" class="btn btn-primary print-label clear-label">Print Label</button>
      </div>
    </div>
  </div><br>
</div>

<script type="text/javascript">
  $('.print-label').click(function(){
    PrintDiv($("#dictation1").val())
  })

  $('.ckeditor1').ckeditor({
    // optional config
  })

  function PrintDiv(text) {
    var popupWin = window.open('', '_blank', 'width=300,height=300');
    popupWin.document.open();
    if (text.indexOf('span') == -1){
      popupWin.document.write('<html><body>' + '<span style="font-family:Comic Sans MS,cursive">' + text + '</span>' + '</html>');
      
    } else {
      popupWin.document.write('<html><body>' + text + '</html>'); 
    }
    
    var document_focus = false;
    $(document).ready(function() { popupWin.window.print();document_focus = true; });
        setInterval(function() { if (document_focus === true) { popupWin.window.close(); }  }, 300);
    // popupWin.document.close();

  }
</script>

app/views/home/dummy.html.erb
<div class="row custom-table-position">
  <div class="well col-md-12 col-sm-12 col-xs-12 reports">
    <div class="col-md-8 col-sm-8 col-xs-8">
      <%= form_tag sheets_path, :method => "get",:remote=> true do %>
        <b>List of Subjects</b>
        <%= select_tag :subject, options_for_select(['ENGLISH', 'MATHS'], 'ENGLISH'),:prompt => "Select Subject", class: 'form-control dummy_subject_id' %><br>
        <div class="filter-subject">
          <b>Previous Objectives</b>
          <%= select_tag :sheet, options_for_select(['ENGLISH TEST1', 'ENGLISH TEST2']),:prompt => "Select Objective", class: 'form-control sheet_subject_id' %><br>
        </div>
      <% end %>
      <button type="button" class="btn btn-sm" style="float:right;" id="record-btn"><span>Start Speech</span></button>
      <div class="form-group form-section">
        <form>
          <div class="col-md-12">
            <div class="col-md-10">
              <%= label_tag 'Denial', nil, :class => "control-label label-name" %>
              <%= text_area_tag :comment, '', class: 'form-control ckeditor2', rows: "5", id: "dictation_test"%>
            </div>
            <div class="col-md-2 col-sm-2">
              <button type="button" class="btn btn-primary print-label" , id="print-label">Print Label</button>
              <button type="button" class="btn btn-primary print-label clear-label">Clear Label</button>
              <button type="button" class="btn btn-primary print-label">Save Label</button>
            </div>
          </div>
          <div class="col-sm-12 col-md-12">
            <div class="col-sm-4 grade-abr">
              <% [['Mastery','A', 'green'], ['Good','AB', 'blue'], ['Excellent', 'A+', 'orange'], ['Poor', 'C', 'yellow']].each do |grade| %>
                <div class="radio radio-margin">
                  <label><%= radio_button_tag :grade_id , grade[0],false, "data-marks" => grade[1], onclick: "getGrade('#{grade[0]}', '#{grade[1]}', '#{grade[2]}')","data-grade" => grade[0].downcase, "data-color" => grade[2] %><%= grade[0] %></label>
                </div>
              <% end %>
            </div>
            <div class="col-md-6 col-sm-6 grade-margin">
              <h5>Current Grade</h5>
              <b><%= text_field_tag :marks, "", class: 'form-control text-size', disabled: true %></b>

            </div>
          </div>
        </form>
      </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-4 student-list">
      <div class="table-responsive">
        <table class="table table-bordered table-striped">
          <tbody>
            <tr>
              <% ['Denial', 'Dean', 'Michael', 'Thomas', 'Sachin', 'Hemant', 'Merry', 'Jacop' 'Weslay','Deepak', 'William', 'Smithson', 'Jessica'].each_slice(10) do |details| %>
                <td>
                  <% details.each do |detail| %>
                    <input type="checkbox" id="detail-id-<%= detail %>" class="multiple-child" onclick="selectMultipleChild('<%= detail %>')" value="<%= detail %>">
                    <%= link_to detail, '', id: detail, class: "child-name", remote: true %><br>
                  <% end %>
                </td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div><br>
</div>

<script type="text/javascript">
  function selectMultipleChild(detailID){
    if ($("#detail-id-"+detailID).is(":checked")){
      $(".child-name").removeClass('active-child');
    }
  }

  function getGrade(name, abr, color){

    if ($("#grade_id_"+name).is(":checked")) {
      $(".text-size").val(abr)
      $(".text-size").css("background-color", color);
    }
  }
  initilize_data()

</script>

app/views/home/index.html.erb
<div class="custom-table-position" style="margin-left: 200px;">
  <div class="text-center welcome-text">Welcome back <span class="color-red"><%= current_teacher.name %></span></div>
  <% if @details_count > 0 %>
    <div class="text-center congratulation-text">In the last 30 days you have marked <span class="color-red"><%= @details_count %></span> pieces of children's work. Congratulations!</div>
  <% end %>
  <div class="">
    <div class="row col-md-12 col-sm-12 text-center" style="margin-top: 19px;">
      <div class="col-md-3 dashboard-img-box text-center">
        <%= link_to(image_tag("Marking.png", height: "120px"), new_sheet_path) %>
        <div class="dashboard-image-text"><b>New Objective</b></div>
      </div>
      <div class="col-md-3 dashboard-img-box text-center align-dashboard-image">
        <%= link_to(image_tag("Markbook.png", height: "120px"), sheets_path) %>
        <div class="dashboard-image-text"><b>Markbook</b></div>
      </div>
      <div class="col-md-3 dashboard-img-box text-center align-dashboard-image">
        <%= link_to(image_tag("Reports.png", height: "120px"), report_sheets_path) %>
        <div class="dashboard-image-text"><b>Assessment</b></div>
      </div>
    </div>
    <div class="row col-md-12 col-sm-12">
      <div class="col-md-2">
      </div>
      <div class="col-md-3 dashboard-img-box text-center" style="margin-left: 29px;">
        <%= link_to(image_tag("Children.png", height: "120px", width: "100%"), children_path) %>
        <div class="dashboard-image-text"><b>Children</b></div>
      </div>
      <div class="col-md-2" style="text-align: right;">
        
      </div>
      <div class="col-md-3 dashboard-img-box text-center" style="margin-left: 32px;">
        <%= link_to(image_tag("subjects.png", height: "120px"), subjects_path) %>
        <div class="dashboard-image-text"><b>Classes</b></div>
      </div>
      <div class="col-md-2" style="text-align: right;">
        
      </div>
    </div>
  </div>
</div>

app/views/home/subscription.html.erb
<div>
  <div class="">
    <div class="row col-md-12 col-sm-12">
      <div class="col-md-6">
        <div style="padding-left:24px; padding-top: 14px;"><%#= link_to 'Individual Plan', new_subscription_path(type: 1) %>
          <%= link_to(image_tag("individual.png"), new_teacher_registration_path(subscription_id: 1)) %>
        </div>
        
      </div>
      <div class="col-md-6" style="text-align: center;">
        <div style="padding-left:24px; padding-top: 14px;">
          <div><%= link_to(image_tag("5users.png"), new_teacher_registration_path(subscription_id: 2)) %></div>
        </div>
      </div>
    </div>
    <div class="row col-md-12 col-sm-12" style="margin-top: 40px;">
      <div class="col-md-6">
        <div style="padding-left:24px; padding-top: 14px;"><div><%= link_to(image_tag("10users.png"), new_teacher_registration_path(subscription_id: 3)) %></div></div>
      </div>
      <div class="col-md-6" style="text-align: center;">
        <div style="padding-left:24px; padding-top: 14px;"><div><%= link_to(image_tag("20users.png"), new_teacher_registration_path(subscription_id: 4)) %></div></div>
      </div>
    </div>
  </div>
</div>

app/views/home/trial.html.erb
<div class="row custom-table-position">
  <div class="well col-md-12 col-sm-12 col-xs-12 reports">

    <div class="col-md-7 col-sm-7 col-xs-7">
      <div class="test" style="display: none; color: red;">Your current browser is not supported. Please use Google Chrome to activate voice recognition.</div>
      <%= form_tag sheets_path, :method => "get",:remote=> true do %>
        <b>List of Subjects</b>
        <%= select_tag :subject, options_for_select(['ENGLISH', 'MATHS'], 'ENGLISH'),:prompt => "Select Subject", class: 'form-control dummy_subject_id' %><br>
        <div class="filter-subject">
          <b>Previous Objectives</b>
          <%= select_tag :sheet, options_for_select(['I can use fronted adverbials.', 'I can use an embedded clause.']),:prompt => "Select Objective", class: 'form-control sheet_subject_id' %><br>
        </div>
      <% end %>
      <button type="button" class="btn btn-sm" style="float:right;" id="record-btn"><span>Start Speech</span></button>
      <div class="form-group form-section trail-page-speech-area">
        <form>
          <div class="col-md-12">
            <div class="col-md-10 trial-form">
              <%= label_tag 'Edward', nil, :class => "control-label label-name" %>
              <%= text_area_tag :comment, '', class: 'form-control ckeditor2', rows: "5", id: "dictation_test"%>
            </div>
            <div class="col-md-2 col-sm-2">
              <button type="button" class="btn btn-primary print-label" , id="print-label">Print Label</button>
              <button type="button" class="btn btn-primary print-label clear-label">Clear Label</button>
              <button type="button" class="btn btn-primary print-label">Save Label</button>
            </div>
          </div>
          <div class="col-sm-12 col-md-12">
            <div class="col-sm-4 grade-abr">
              <% [['Grade 1','1', 'skyblue'], ['Grade 2','2', 'green'], ['Grade 3', '3', 'orange'], ['Grade 4', '4', 'red']].each do |grade| %>
                <div class="radio radio-margin">
                  <label><%= radio_button_tag :grade_id , grade[0],false, "data-marks" => grade[1], id: 'grade_id_'+grade[1], onclick: "getGrade('#{grade[0]}', '#{grade[1]}', '#{grade[2]}')","data-grade" => grade[0].downcase, "data-color" => grade[2] %><%= grade[0] %></label>
                </div>
              <% end %>
            </div>
            <div class="col-md-6 col-sm-6 grade-margin">
              <h5>Current Grade</h5>
              <b><%= text_field_tag :marks, "", class: 'form-control text-size', disabled: true %></b>

            </div>
          </div>
        </form>
      </div>
    </div>

    <div class="col-md-5 col-sm-5 col-xs-5 student-list">
      <div class="table-responsive">
        <table class="table table-bordered table-striped">
          <tbody>
            <tr>
              <% ['Edward', 'William', 'Daniel', 'Thomas', 'Lucy', 'Claire', 'Jessica', 'Michael', 'Laura'].each_slice(9) do |details| %>
                <td>
                  <% details.each do |detail| %>
                    <input type="checkbox" id="detail-id-<%= detail %>" class="multiple-child" onclick="selectMultipleChild('<%= detail %>')" value="<%= detail %>">
                    <%= link_to detail, '', id: detail, class: "child-name", remote: true %><br>
                  <% end %>
                </td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
  <div style="width:100%;height:0px;position:relative;padding-bottom:56.250%;"><iframe src="https://streamable.com/s/k0987/gaeczu" frameborder="0" width="100%" height="100%" allowfullscreen style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>
    <div>
      <div class="sign-up-trial-btn">
        <a href="/teachers/sign_up" class="btn btn-info btn-lg trial-sign-up-button">Sign Up</a>
      </div>
      <div>30 Day Free Trial, including</div>
      <div class="free-printer-text">free label printer</div>
    </div>
</div>
  </div><br>
</div>



<!-- Modal -->
<div class="modal fade" id="memberModal" tabindex="-1" role="dialog" aria-labelledby="memberModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close close-popup" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
          </button>
           <h4 class="modal-title" id="memberModalLabel">Thank you for trying Mark Mate.</h4>
      </div>
      <div class="modal-body">
          <p>Full version features
            <BR>- Customisable Grades.
            <BR>- Unlimited Classes and Objectives.
            <BR>- Admin account to manage school teacher accounts.
            <BR>- Markbook assessment showing grades and feedback.
            <BR>- Blank label feature to print extension questions during lessons.
          </p>
          <p>You will now be shown the trial site.</p>
          <p><a href="#" class="tooltip-test" title="Example">WATCH AN EXAMPLE</a></p>
          <div style="width:100%;height:0px;position:relative;padding-bottom:56.250%;" class="stop-vedio"><iframe src="https://streamable.com/s/k0987/gaeczu" frameborder="0" width="100%" height="100%" allowfullscreen style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>
      </div>
      <div class="modal-footer">
        <div class="row">
          <div class="col-md-6 col-xs-6">
            <div class="trial-free-text">
            <a href="/teachers/sign_up" class="btn btn-info btn-lg trial-sign-up-button">Sign Up</a>
            <div class="">30 Day Free Trial, including free label printer</div>
            <div></div>
            </div>
          </div>
          <div class="col-md-6 col-xs-6">
            <button type="button" class="btn btn-primary close-popup" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function () {
    $('#memberModal').modal('show');
    if (!annyang) {
      $('.test').show();
    }else {
      $('.test').hide();
    }
    $('.close-popup').click(function(e) {
      e.preventDefault();
      $(".stop-vedio").children('iframe').attr('src', '');
    })
  });
  function selectMultipleChild(detailID){
    if ($("#detail-id-"+detailID).is(":checked")){
      $(".child-name").removeClass('active-child');
    }
  }

  function getGrade(name, abr, color){

    if ($("#grade_id_"+abr).is(":checked")) {
      $(".text-size").val(abr)
      $(".text-size").css("background-color", color);
    }
  }
  initilize_data()

</script>