config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #devise_for :teachers
  devise_for :teachers, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'subscription_plan', :to => 'home#subscription'
  get 'blank_label', to: 'home#blank_label'
  get 'trial', to: 'home#trial'

  resources :subjects do
    collection do
      get :fetch_children
    end 
  end
  resources :children
  resources :teachers do
    collection do
      post  :create_teacher
      get :teacher_subscription
    end
  end
  resources :sheets do
    collection do
      get :fetch_children
      get :report
      get :report_details
    end 
    member do
      get :child_detail
      patch :update_detail
    end
  end

  resources :subscriptions do
    collection do
      post :checkout
      get :thankyou
    end
  end
  get '*path' => redirect('/')
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  attr_accessor :created_by, :users, :period, :subscription_plan, :marked
  has_many :subjects, :dependent => :destroy
  has_many :children, :dependent => :destroy
  has_many :sheets, :dependent => :destroy
  has_many :sub_teachers, :class_name => 'Teacher', :foreign_key => :parent_id
  has_many :subscriptions, :dependent => :destroy
  has_many :details, through: :sheets
  #belongs_to :parent_teacher, :class_name => 'Teacher', :foreign_key => :parent_id

  after_save :save_subscription
  #after_create :send_reset_password_link
  ROLES = { headTeacher: 'HeadTeacher', subTeacher: 'SubTeacher' }


  def is_head?
    role == ROLES[:headTeacher]
  end

  def is_teacher?
    role == ROLES[:subTeacher]
  end

  def parent_teacher
    Teacher.find_by_id(parent_id)
  end

  def plan
    subscriptions.is_active.first
  end

  def is_plan_active?
    teacher_plan = is_teacher? ? parent_teacher.plan : plan
    if teacher_plan.present?
      if teacher_plan.period == "yearly"
        teacher_plan.status && (Time.zone.now < teacher_plan.payment_date + 1.year)
      elsif teacher_plan.period == "monthly"
        teacher_plan.status# && (Time.zone.now < teacher_plan.payment_date + 1.month)
      end
    end 
  end

  private

  def send_reset_password_link
    send_reset_password_instructions
  end 

  def save_subscription
    if users.present? && admin_id?
      subscriptionType = SubscriptionType.find(5)
      subscription = subscriptionType.subscriptions.find_or_create_by({teacher_id: id})
      subscription.update_attributes(period: period, no_of_users: users, payment_status: 'Completed', payment_date: Time.now, status: subscription_plan, payment_type: 'Cash')
    elsif plan.present? && subscription_plan
      plan.update_column(:status, subscription_plan)
    end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  load_and_authorize_resource :except => [:show]
  before_action :check_plan, only: [:new, :create_teacher, :update]

  def index
    @teacher = current_teacher
  end

  def new
  end

  def create_teacher
    @teacher = current_teacher.sub_teachers.new(teacher_params)
    if @teacher.save
      @success = ["Teacher was successfully created."]
    else
      @errors = @teacher.errors.full_messages
    end
    fetch_sub_teacher
  end

  def edit
  end

  def update
    if @teacher.update(teacher_params)
      @success = ["Teacher was successfully updated."]
    else
      @errors = @subject.errors.full_messages
    end
    fetch_sub_teacher
  end

  def destroy
    @teacher.destroy
    fetch_sub_teacher
  end

  def teacher_subscription
  end

  private

  def teacher_params
    params.require(:teacher).permit(:name, :email, :password, :password_confirmation, :role)
  end

  def fetch_sub_teacher
    @teachers = current_teacher.sub_teachers
  end

  def check_plan
    if current_teacher.plan.is_individual?
      flash[:notice] = "You are not eligible for create teachers because your current plan is individual"
      render :js => "window.location = '/'"
    elsif current_teacher.plan.no_of_users == current_teacher.sub_teachers.count
      flash[:notice] = "Your no of users limit is over"
      render :js => "window.location = '/'"
    end
  end
end

app/views/teachers/_form.html.erb
<div id="teacher-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="error_section">
      </div>
      <%= form_for @teacher, url: teacher_redirect_url, remote: true, html: { style: "display:inline;"} do |f| %>
        <div class="modal-body">
          <ul class="errors"></ul>
          <div class="form-group">
            <%= f.label :name %><br />
            <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Name', required: true %>
          </div>
          <div class="form-group">
            <%= f.label :email %><br />
            <%= f.email_field :email, autocomplete: "email", class: 'form-control', placeholder: 'Email', required: true %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Password', required: true %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', required: true %>
          </div>
          <%= f.hidden_field :role, value: 'SubTeacher'%>
        </div>
        <div class="modal-footer">
          <%= f.submit class: "btn btn-primary" %>
          <%= link_to "Cancel", "#", class: "btn btn-default", data: {dismiss: "modal"} %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/teachers/_teacher.html.erb
<div class="teacher-list">
  <% if @teachers.present? %>
    <div class="table-responsive">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th class="text-center">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @teachers.each do |teacher| %>
            <tr>
              <td><%= teacher.name %></td>
              <td><%= teacher.email %></td>
              <td class="text-center">
                <%= link_to "Edit", edit_teacher_path(teacher), remote: true, class: "btn btn-default" %>
                <%= link_to 'Delete', teacher_path(teacher), :method => :delete, data: { confirm: 'Are you sure?' }, remote: true, class: "btn btn-default" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/teachers/create_teacher.js.erb
$('.error_section').html("<%= escape_javascript( render :partial => '/layouts/message_flash') %>")
<% unless @errors.present? %>
  $(".teacher-list").html("<%= escape_javascript(render 'teacher') %>")
  $("#teacher_name, #teacher_email, #teacher_password, #teacher_password_confirmation").val('')
  $("#sub-teacher-stats").html("<%= @teachers.count %>")
<% end %>

app/views/teachers/destroy.js.erb
$(".teacher-list").html("<%= escape_javascript(render 'teacher') %>")
$("#sub-teacher-stats").html("<%= @teachers.count %>")

app/views/teachers/edit.js.erb
$('#teacher-form').html('<%= j render "teachers/form" %>')
$("#teacher-modal").modal()

app/views/teachers/index.html.erb
<div class="row custom-table-position">
  <div class="well">
    <%= link_to 'Add Teacher', new_teacher_path, remote: true %>
    <span style="float: right;">
    	<!-- <span style="color: #337ab7">Total:</span><span><%= @teacher.plan.no_of_users %></span>&nbsp;&nbsp;
    	<span style="color: #337ab7">Remaining:</span><span id="sub-teacher-stats"><%= @teachers.count %></span> -->
    </span>
  </div>
  <div id="teacher-form"></div>
  <%= render "teacher" %>
</div>

app/views/teachers/new.js.erb
$('#teacher-form').html('<%= j render "teachers/form" %>')
$("#teacher-modal").modal()

app/views/teachers/teacher_subscription.html.erb
<div class="custom-table-position" style="margin-left: 200px;">
  <% if current_teacher.subscriptions.is_active.present? %>
    <div class=well>
      Your current plan is <%= current_teacher.subscriptions.is_active.first.subscription_type.name%>
    </div>
  <% end %>
</div>

app/views/teachers/update.js.erb
$('.error_section').html("<%= escape_javascript( render :partial => '/layouts/message_flash') %>")
<% unless @errors.present? %>
  $(".teacher-list").html("<%= escape_javascript(render 'teacher') %>")
<% end %>